### ISSUE TITLE
Pokemon Grass World Gen Crash

### ISSUE THREAD

**Issue by Stampede2011** [Dysth/Generations#187] opened 2021-06-12 16:29 UTC
**What is the bug?**
Upon loading new terrain, the world can sometimes crash. According to the crash report, it looks related to the new Pokemon Grass generation.

**What are the steps to reproduce the bug?**
Inconsistent to produce. Happens when teleporting into or generating new terrain.

**What version of Pixelmon and Forge are you on?**
Pixelmon v8.5.0 and Forge 14.23.5.2854

**Please provide any screenshots or crash reports if needed.**
Multiple Crash Reports below:
[crash-2021-06-12_00.03.55-server.txt](https://github.com/Deltric/Generations/files/6642539/crash-2021-06-12_00.03.55-server.txt)
[crash_on_console.txt](https://github.com/Deltric/Generations/files/6642542/crash_on_console.txt)
[crash-2021-06-12_18.18.27-server.txt](https://github.com/Deltric/Generations/files/6642543/crash-2021-06-12_18.18.27-server.txt)

**Comment by ShadowWulff** [comment] 2021-06-12 16:51
Still confused

**Comment by Dysth** [comment] 2021-06-13 00:03
8.5.1 will have a generatePokeGass hocon setting, to disable it for those few that are having issues while we take more time to investigate the cause

**Comment by Blackkie** [comment] 2021-06-21 03:43
@Stampede2011 @Dysth and how can I disable that thing?

**Comment by Blackkie** [comment] 2021-06-22 04:48
> 
> 
> @Stampede2011 @Dysth and how can I disable that thing?

ok, I already disabled generatePokeGass in the pixelmon hocon file and seems like the problems are fixed now. thx.

**Closed** 2022-06-21 17:25 UTC
Labels: bug, beta-testing
